version: "3"

services:

  auth:
    container_name: auth
    build: ./auth
    ports:
      - 4000:4000
    restart: always
    environment:
      - ENV

  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pg-admin:
    container_name: pgadmin
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050

volumes:
  postgres_data:
    driver: local
    